#
# Notes
#
# Cirrus CI has a concurrency limit of 24 CPU cores for open source projects.
# This means we should not have more than 12 pipelines with more than 2 CPUs
# in each pipeline running parallel
#
# Documentation:
# - https://cirrus-ci.org/examples/
# - https://cirrus-ci.org/guide/writing-tasks/
#

# TODO:
# - https://github.com/marketplace/actions/create-pull-request
# - https://peterevans.dev/posts/github-actions-how-to-create-pull-requests-automatically/
#
# - https://forge.rust-lang.org/infra/other-installation-methods.html#rustup

---

#
# Templates
#

# Constants

elk_task_timeout_template: &ELK_TASK_TIMEOUT
  timeout_in: 10m # This needs to be reasonable large in order not to run in a timeout in the docker image re-builds

elk_common_cpu_and_memory_config_for_build_and_test_template: &ELK_COMMON_CPU_AND_MEMORY_CONFIG_FOR_BUILD_AND_TEST
  cpu: 2
  memory: 4GB

# Container

elk_container_ubuntu_22_04_x64_template: &ELK_CONTAINER_UBUNTU_22_04_X64
  <<: *ELK_TASK_TIMEOUT
  container:
    dockerfile: internal/docker/ubuntu-22.04
    <<: *ELK_COMMON_CPU_AND_MEMORY_CONFIG_FOR_BUILD_AND_TEST

elk_container_windows_server_2019_x64_template: &ELK_CONTAINER_WINDOWS_SERVER_2019_X64
  <<: *ELK_TASK_TIMEOUT
  windows_container:
    dockerfile: internal/docker/windowsservercore-2019
    <<: *ELK_COMMON_CPU_AND_MEMORY_CONFIG_FOR_BUILD_AND_TEST

# Build and Teset

elk_common_build_and_test_debug_template: &ELK_COMMON_BUILD_AND_TEST_DEBUG
  env:
    RUSTDOCFLAGS: -D warnings
  build_script: cargo build --workspace --all --examples
  doc_script: cargo doc
  test_script: cargo test --workspace --all

elk_common_build_and_test_release_template: &ELK_COMMON_BUILD_AND_TEST_RELEASE
  env:
    RUSTDOCFLAGS: -D warnings
  build_script: cargo build --release --workspace --all --examples
  doc_script: cargo doc --release
  test_script: cargo test --release --workspace --all

elk_windows_build_and_test_debug_template: &ELK_WINDOWS_BUILD_AND_TEST_DEBUG
  env:
    RUSTDOCFLAGS: -D warnings
  build_script: cargo build --workspace --all --benches
  doc_script: cargo doc
  test_script: cargo test --workspace --all

elk_windows_build_and_test_release_template: &ELK_WINDOWS_BUILD_AND_TEST_RELEASE
  env:
    RUSTDOCFLAGS: -D warnings
  build_script: cargo build --release --workspace --all --benches
  doc_script: cargo doc --release
  test_script: cargo test --release --workspace --all

#
# Ubuntu x86
#

preflight_check_task:
  <<: *ELK_CONTAINER_UBUNTU_22_04_X64
  # registry_cache:
  #   folder: $CARGO_HOME/registry
  #   fingerprint_script: cat Cargo.lock
  # target_cache:
  #   folder: target
  #   fingerprint_script:
  #     - rustc --version
  #     - cat Cargo.lock
  set_toolchain_script: rustup default beta
  <<: *ELK_COMMON_BUILD_AND_TEST_DEBUG
  # before_cache_script: rm -rf $CARGO_HOME/registry/index

ubuntu_nighlty_task:
  depends_on: preflight_check
  <<: *ELK_CONTAINER_UBUNTU_22_04_X64
  set_toolchain_script: rustup default nightly
  <<: *ELK_COMMON_BUILD_AND_TEST_RELEASE


windows_server_2019_x64_stable_debug_task:
  depends_on: preflight_check
  <<: *ELK_CONTAINER_WINDOWS_SERVER_2019_X64
  dummy_script:
    - ls C:\cargo
    - ls C:\cargo\bin
    - ls C:\rustup
    - C:\cargo\bin\rustup default stable
    - C:\cargo\bin\cargo --version
    - git clone https://github.com/larry-robotics/elkodon
    - cd elkodon
    - C:\cargo\bin\cargo build --workspace --all --examples
    - echo $env:PATH
    - cargo --version
  <<: *ELK_WINDOWS_BUILD_AND_TEST_DEBUG

windows_server_2019_x64_stable_release_task:
  depends_on: windows_server_2019_x64_stable_debug
  <<: *ELK_CONTAINER_WINDOWS_SERVER_2019_X64
  <<: *ELK_WINDOWS_BUILD_AND_TEST_RELEASE
